### ISSUE TITLE
I can't see any star icon on the transcript bar while using your Extension. 

### ISSUE THREAD

**Issue by treefairyz** [dobladov/youtube2Anki#1]
Sorry. But I can't see any star icon on the transcript bar while using your Extension. How can I use your Extension properly?

**Comment by dobladov** [comment]
Thanks for using version 0.0.1! :+1:  this was more of an alpha version than a proper release, I just updated the extension for both Chrome and Firefox with some fixes, please be sure to **use now 0.0.2** and try again.

If you keep having problems please tell me which browser and version are you using.

**Comment by treefairyz** [comment]
Thanks for your rapid response! I can now use your extension with Chrome and Firefox. That's very kind of you to do so! It is such a brilliant extension. It is very helpful for language learning as well as video course notes.Thanks a lot for your contribution! Great job!!!!

**Comment by dobladov** [comment]
It makes me really happy to see that is working and you find it useful!

This extension might be quite unstable due to frequent changes of YouTube, please report any problems or ideas you might have, I will try my best to keep it working.

Thanks for using my software.
