### ISSUE TITLE
Youtube link broken

### ISSUE THREAD

**Issue by SpaceGhost21** [dobladov/youtube2Anki#10]
<img width="1008" alt="Screen Shot 2021-05-03 at 10 28 54 PM" src="https://user-images.githubusercontent.com/83630512/116964260-f0fe4b80-ac5f-11eb-840f-71f7a1fe7bce.png">

I followed the instructions, but I'm getting a message on Anki saying the YouTube video is unavailable. Help?

**Comment by dobladov** [comment]
Is it happening with all YouTube videos? It looks to me that this video does not allow embedding it.
Can you share the link to the video so I can test it too?
