### ISSUE TITLE
Ankiconnect connect not possible 

### ISSUE THREAD

**Issue by OliverRovesik** [dobladov/youtube2Anki#11]
Hi, the extension doesn't work on my Chrome Browser, MacBook M1. 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/83225053/121829500-4b75d780-ccf5-11eb-8f23-46d750462b70.png"> 
I've added "*" on Ankiconnet configuration but it still doesn't work. However, Ankiconnect works well on other extensions

**Comment by Oafish1** [comment]
Hello!  I was having the same problem.  I don't have a solution, but I do have another way to get the addon to work with AnkiConnect.

If you download the addon from version [0a75e](https://github.com/dobladov/youtube2Anki/tree/0a75e93fe2dca0d4d6e04edebea95ea794adb1f0) on github, then change the first line of popup.js to
`const connectionMessage = document.getElementById("connectionMessage")`
and change lines 46 and 71 of `youtube2Anki.js` to read
`document.querySelector("h1.title").firstChild.innerText`.

Then, for
**Firefox:** Go to `about:debugging` > This Firefox > Load Temporary Add-on > Click any file in the `src` folder _(NOTE: This will only install the addon temporarily.  For permanent addition, you need to package the extension and open it with Firefox)_
**Chrome:** Go to `chrome://extensions/` > Developer mode: ON > Load unpacked > Select the `src` folder

**Comment by dobladov** [comment]
Fixed now for both Firefox and Chrome
