### ISSUE TITLE
Title Header Causing Issues

### ISSUE THREAD

**Issue by Oafish1** [dobladov/youtube2Anki#12]
Hello!  Thank you for making this.

Neither of the addons (Firefox/Chrome) work for me out of the box.  This seemed to be because `title` was being returned as `null` since `document.querySelector("h1").firstChild.innerText` finds nothing.

However, a slight modification to `document.querySelector("h1.title").firstChild.innerText` on lines 46 and 71 of `youtube2Anki.js` from version [0a75e](https://github.com/dobladov/youtube2Anki/tree/0a75e93fe2dca0d4d6e04edebea95ea794adb1f0) (two pulls ago) fixed everything for me.

This version also needed the first line of `popup.js` to be changed from 
`const connectionMessage = document.getElementById("connectionMessages")`
to
`const connectionMessage = document.getElementById("connectionMessage")`
which you already addressed in later versions.

**Comment by Oafish1** [comment]
Awesome!  Looking forward to it.  Loving the addon.

**Comment by dobladov** [comment]
I already submitted the changes for Chrome, it should be updated after it passes the review process.
Unfortunately Firefox does not support manifest v3 yet, so I might create a patch version instead of a new release for this browser.

**Comment by dobladov** [comment]
Submitted now a fixed version with Firefox, unfortunately it will not have the new functionality just bug fixes.

**Comment by dobladov** [comment]
The new Chrome version is now published.
