### ISSUE TITLE
Pop-up closing immediately after open

### ISSUE THREAD

**Issue by lucianosarno** [dobladov/youtube2Anki#17]

**Comment by lucianosarno** [comment]
https://www.loom.com/share/a94d373d20ee4709bf31ebf550d277cc
here a short video showing that (apparently) nothing happens, but it seems that the popup opens and closes instantaneously

**Comment by dobladov** [comment]
I already fixed the bug, but the new version is being reviewed by Google before going live (it was submitted last Saturday).
If you need the plugin working for Chrome, please be patient.

Right now only the Firefox version is working: https://addons.mozilla.org/en-US/firefox/addon/youtube2anki/

**Comment by dobladov** [comment]
The new version is now publish, please give it another try
