### ISSUE TITLE
Didn't find star buttons

### ISSUE THREAD

**Issue by CollinsPeriodLee** [dobladov/youtube2Anki#2]
Hi, thanks for your great add-ons, I did't find the star button. I've tried both chrome and firefox. Here are screenshots.
![image](https://user-images.githubusercontent.com/22069889/60232770-37641180-9863-11e9-8d5b-d8fad473fa6e.png)

Above is chrome, Below is firefox.
![image](https://user-images.githubusercontent.com/22069889/60232809-51055900-9863-11e9-8d69-12f682a98572.png)
![image](https://user-images.githubusercontent.com/22069889/60232835-67131980-9863-11e9-8266-b6e5cd288bdf.png)

The chrome version is Version 75.0.3770.100 (Official Build) (64-bit)
The firefox version is 67.0.4 (64-bit)

Really thanks for your help!

**Comment by dobladov** [comment]
Try to reload the link to the video (https://www.youtube.com/watch?*) instead of navigating to the video from another page, is a little bit tricky how to attach the star button, if it keeps not working for you, I will try to find an alternative way to do it.

**Comment by CollinsPeriodLee** [comment]
No, reloading the link still doesn't work for me.

**Comment by dobladov** [comment]
In that case, try to see if there is any error on your console that might help me to find the problem, press F12 to show it.

I'm planing to do a lot of refactoring of the code given the feedback of some user, so in the future might work for you too.

**Comment by dobladov** [comment]
I made a complete refactor for how the subtitles are generated, now the star icon is not required, please, give it another try, I hope now it works for you.

![example](https://user-images.githubusercontent.com/1938043/60365436-00b80380-99e9-11e9-8524-02916a2619a9.gif)

**Comment by CollinsPeriodLee** [comment]
Thanks, I updated and tried the new way, it still doesn't work for me. Below is the error reported.
 
![image](https://user-images.githubusercontent.com/22069889/60376223-073b8080-99d3-11e9-97ae-f86e1824501e.png)
![image](https://user-images.githubusercontent.com/22069889/60376258-3b16a600-99d3-11e9-92f1-96d16bb973fb.png)

**Comment by CollinsPeriodLee** [comment]
I opened the transcript before I clicked the icons.
![image](https://user-images.githubusercontent.com/22069889/60376297-829d3200-99d3-11e9-8028-6a06f9921077.png)

**Comment by CollinsPeriodLee** [comment]
I found the bug.
![image](https://user-images.githubusercontent.com/22069889/60377635-4cb17b00-99de-11e9-982d-dda322eac1a1.png)
Here, I deleted `ytd-engagement-panel-section-list-renderer #body`, then it worked. Thank you for your great add-ons!

**Comment by dobladov** [comment]
I should apply your solution, I was using `ytd-engagement-panel-section-list-renderer` as the way to attach the star, but I also had problems in the past since they kept changing the name of this tag.

I'm glad to see is working for you now, thanks for the feedback.

**Comment by dobladov** [comment]
I shipped your solution with version `0.0.7`, thanks again!
