### ISSUE TITLE
Could you add the video title automatically. I can do it manually. But if your extension can add the title automatically, that will save a lot of time.

### ISSUE THREAD

**Issue by treefairyz** [dobladov/youtube2Anki#3]

**Comment by dobladov** [comment]
It should be easy to do since I already use the title for the name of the csv file.

**Comment by dobladov** [comment]
I included the title at the end of the csv, don't forget to add the **new field in the note type** and **{{title}} to the card template** like a mention in the updated [instructions](https://github.com/dobladov/youtube2Anki#instructions).

Let me know if it works with version 0.0.5 to close this issue.

**Comment by treefairyz** [comment]
Your extension works perfectly. Great contribution! You save me a lot of time! Wish you have a lot of fun time in life!
