### ISSUE TITLE
Subtitles added to Anki are missing!

### ISSUE THREAD

**Issue by Superruma** [dobladov/youtube2Anki#36]
I added the entire subtitle of a video from youtube to Anki. And after studying, I went back to youtube and realized it was missing some parts! So I tried adding those parts but it didn't work! Looks like Youtube2Anki has encountered some errors! Please fix it because I love this extension!

**Comment by dobladov** [comment]
Can you please add the link to the video so I can check what's the issue, thanks

**Comment by Superruma** [comment]
> Can you please add the link to the video so I can check what's the issue, thanks

https://youtu.be/ewoQpAWx9jE

It's missing at 0:21, 3:13, 3:23, 3:37 and 3:39!

**Comment by dobladov** [comment]
It creates all the subtitles for me, there are only 29 in the transcript lines in the video and the extension is exporting 29.

[THE SOUND OF SWEDEN.csv](https://github.com/dobladov/youtube2Anki/files/9847188/THE.SOUND.OF.SWEDEN.csv)

If you open a new lesson on Anki it might only show 20 subtitles at once, please make sure you look in browse, you should have all subtitles there.

<img width="860" alt="Screenshot 2022-10-23 at 19 57 44" src="https://user-images.githubusercontent.com/1938043/197408032-2d3f39f4-a76d-4a58-8f5c-02ba70a7e81c.png">

**Comment by Superruma** [comment]
> If you open a new lesson on Anki it might only show 20 subtitles at once, please make sure you look in browse, you should have all subtitles there.

You try merging some sentences! It's missing! I guess maybe the error is there 

(I use Microsoft Edge browser on macbook)!

Link: https://youtu.be/UqU19dR0bFE
<img width="400" alt="Screen Shot 2022-10-24 at 1 11 15 AM" src="https://user-images.githubusercontent.com/116511576/197408799-c95fa84d-02c4-4262-887b-0a757837bfad.png">
<img width="641" alt="Screen Shot 2022-10-24 at 1 11 40 AM" src="https://user-images.githubusercontent.com/116511576/197408811-d46edc7b-9002-41e0-abb0-9e34c87290c2.png">

**Comment by Superruma** [comment]
> It creates all the subtitles for me, there are only 29 in the transcript lines in the video and the extension is exporting 29.
> 
> [THE SOUND OF SWEDEN.csv](https://github.com/dobladov/youtube2Anki/files/9847188/THE.SOUND.OF.SWEDEN.csv)
> 
> If you open a new lesson on Anki it might only show 20 subtitles at once, please make sure you look in browse, you should have all subtitles there.
> 
> <img alt="Screenshot 2022-10-23 at 19 57 44" width="860" src="https://user-images.githubusercontent.com/1938043/197408032-2d3f39f4-a76d-4a58-8f5c-02ba70a7e81c.png">

I just tried it again! Seems to be my browser or OS! (Microsoft Edge and Mac OS)

**Comment by dobladov** [comment]
I will check Edge on mac os, thanks for reporting

**Comment by Superruma** [comment]
Hi doblado! Have a good day!

About some bug in youtube2 anki that i mentioned yesterday!

I tried! It seems all browsers on Mac os are buggy! All are missing!

**Comment by dobladov** [comment]
I'm using mac as well

**Comment by dobladov** [comment]
> What browser (Chrome, Opera,...ect) do you use?

I'm using Google Chrome on the latest mac version

> Does anki application require any other add-ons besides anki connect?

No

Check the download function of youtube2anki, if you get the 29 subtitles, the problem is not in the extension.
It could be that Anki connect or your version of Anki causes the problem.

**Comment by Superruma** [comment]
Dear Dobladov!

Thank you for your reply!

I have tried deleting and reinstalling!  The first time you add it, it will
add enough cards.  But the next time will be missing some cards!

**Comment by dobladov** [comment]
I can confirm the issue now, I'm not sure why it happens yet, probably some special characters that need to be cleaned up before sending to Anki.

The extension is exporting all the subtitles correctly, but they might not be valid for Anki.

Thanks, I will look into this problem when I have some free time.

**Comment by Superruma** [comment]
Ja! Thank you so much!
