### ISSUE TITLE
How to choose the deck and close youtube's subtitles?

### ISSUE THREAD

**Issue by JunchenZheng** [dobladov/youtube2Anki#44]
Before sending what I choose to Anki, I want to choose my deck. Apparently, as we can see in the picture, the only one I can choose is to create a new deck according to the video's title. 
<img width="436" alt="image" src="https://user-images.githubusercontent.com/125248335/222965476-02f12488-b2dd-4d6c-825a-927bfcf8842a.png">

Here is another question.
When I review the card, I don't want to see the subtitle. I tried to turn it off but it doesn't work. I mean when I reopen it, the setting of subtle is on by default. Do you have any ideas about how to turn it off?
<img width="703" alt="image" src="https://user-images.githubusercontent.com/125248335/222965753-3d7f0beb-b057-4622-b94b-dc4287bd0f48.png">

**Comment by dobladov** [comment]
For the first issue you can press the arrow down that is on the right to see the other decks without any text, the field acts as a search and only shows the decks that match.

<img width="408" alt="Screenshot 2023-03-05 at 20 53 24" src="https://user-images.githubusercontent.com/1938043/222982584-d7c75341-32bd-4e08-a5ec-4890e1c79eb5.png">

For the second one, you'll have to modify the youtube2anki card to display your preferred information.
`Tools` -> `Manage note types` -> `Youtube2AnkiV2` -> `Cards`

<img width="1252" alt="Screenshot 2023-03-05 at 20 54 33" src="https://user-images.githubusercontent.com/1938043/222982616-59301007-4874-47a7-b152-d30770663f97.png">

**Comment by JunchenZheng** [comment]
@dobladov 
Thanks for your reply.  Both previous questions are solved.

But I’m afraid I need you to answer two more questions before closing the post.

As we can see in the demonstration video, the transcripts always start from the beginning. Can we search the keyword to locate the specific time? I have to scroll through the whole list in some long-time videos to find what I want.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/125248335/223040498-dbc02b44-3596-4ff7-a308-280314b6d54f.png">

Regarding the second one, I'm not sure if it's a bug or just a youtube setting.

It's not that I am reluctant to spend time googling the problem. For some reason, I cannot use youtube freely. So, I do know little about youtube. So I need your help to provide a solution here.

When I first opened the video, the language item is Chinese. So I changed it to English（the red arrow here means English）, the transcripts on the right have been modified,  but the words in the youtube2Anki remained the same.

If I refresh the page, all the transcripts are back to Chinese again.

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/125248335/223040270-1367c13e-1eeb-4ada-aa6f-826325a958a4.png">

**Comment by dobladov** [comment]
For the first one, unfortunately there's no way to search in Youtube2Anki, best option I can offer here is to use the browser search in the YouTube page (Control/Cmd + F) to identify the correct time in the transcript and then find it again in youtube2anki manually, I would like to implement a search function, but it will be challenging to make it performant with long subtitles like movies.

For the second one, YouTube does not save your transcript preference, if you want to refresh the current subtitles you can press the button "Delete saved cards" to refresh them with the current ones selected in Youtube.

<img width="444" alt="Screenshot 2023-03-06 at 09 38 12" src="https://user-images.githubusercontent.com/1938043/223058942-996915f5-63db-409a-9225-0af013b9ae09.png">
